dataBaseURL =jdbc:postgresql://localhost/paw
dataBaseUser =postgres
dataBasePassword =root

webappUrl=http://localhost:8080

inProduction=false

spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
